### ISSUE TITLE
При быстром переключении треков RPC ломается

### ISSUE THREAD

**Issue by donelofficial** [Maks1mio/YMusic-DRPC#18]
Если быстро переключать треки в Я.Музыке, то с высокой долей вероятности RPC в дискорде зависнет, а в консоль выпадет ошибка:
2024-03-11 14:40:06,213 [ERROR] An error occurred: Unknown error
Traceback (most recent call last):
  File "C:\Users\pro10\AppData\Local\Programs\YMusic-DRPC\YandexDiscordRPC\main.py", line 54, in run_discord_rpc
    update_discord_rpc(RPC, data)
  File "C:\Users\pro10\AppData\Local\Programs\YMusic-DRPC\YandexDiscordRPC\lib\discord_rpc_manager.py", line 40, in update_discord_rpc
    RPC.update(
  File "C:\Users\pro10\AppData\Local\Programs\Python\Python310\lib\site-packages\pypresence\presence.py", line 34, in update
    return self.loop.run_until_complete(self.read_output())
  File "C:\Users\pro10\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\pro10\AppData\Local\Programs\Python\Python310\lib\site-packages\pypresence\baseclient.py", line 88, in read_output
    raise ServerError(payload["data"]["message"])
pypresence.exceptions.ServerError: Unknown error

В таком случае помогает только перезапуск скрипта. Возможно проблема в ограничении дискорда на частоту обновления данных, точно сказать не могу. Возможно ли это исправить?

**Comment by Maks1mio** [comment]
Да у дискорда есть ограничения да и проблемы с кодом, приложение будет переезжать на electron. Issues #25
